version: '3.8'

volumes:
  postgres_data:


services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  admin:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env