version: '3.8'


services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  admin:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - static:/code/static
    env_file:
      - ./.env

  nginx:
    image: nginx:1.20
    depends_on:
      - admin
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/site/static
    ports:
      - "80:80"

volumes:
  postgres_data:
  static: